version: "3.8"
services:
  backend:
    image: ${DOCKERHUB_USERNAME}/devops-lab3-backend:latest
    ports:
      - "3001:3001"

  frontend:
    image: ${DOCKERHUB_USERNAME}/devops-lab3-frontend:latest
    ports:
      - "3000:3000"
